/**
 * Placeholder — will be auto-generated by `pnpm db:types`
 * after running supabase/migrations/0001_foundation.sql
 */
export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: {
      user_role: "customer" | "buyer" | "seller" | "business" | "courier" | "franchise" | "admin";
      shipment_size: "M" | "L" | "XL";
      temp_mode: "istabas" | "atdzesets" | "saldets" | "karsts";
      shipment_status: "izveidots" | "apmaksats" | "pienemts" | "cela" | "pakomata" | "izsniegts" | "atcelts";
      delivery_status: "pieejams" | "rezervets" | "savakts" | "piegadats" | "atcelts";
      payment_status: "gaida" | "apmaksats" | "atmaksats" | "neizdevas";
      compartment_status: "brivs" | "rezervets" | "aiznemts" | "serviss";
    };
  };
};
