-- AUTO-GENERATED by scripts/deactivate-zero-price.mjs
-- Pauses listings with price = 0 (or NULL). The seller dashboard
-- shows a 'Cena nav norādīta' banner per affected listing so the
-- seller can fix the price and reactivate.

UPDATE listings
SET status = 'paused'
WHERE (price = 0 OR price IS NULL) AND status = 'active';