-- AUTO-GENERATED by scripts/sync-seller-dropoff.mjs
-- Forces all listings for "WILD’N’FREE" onto drop-off pakomāts "agenskalna".
-- This seller is legally located elsewhere but physically drops stock here,
-- so courier zone (MAX of seller and buyer zone) must use the drop-off pakomāts.

UPDATE listings
SET locker_id = 'agenskalna'
WHERE seller_id = '649f58aa-fc57-4ec4-9ec9-c76fbb77e5e9'
  AND (locker_id IS DISTINCT FROM 'agenskalna');
