-- AUTO-GENERATED by scripts/sync-all-dropoffs.mjs
-- Forces every seller's listings onto their actual drop-off pakomāts so
-- courier pricing (MAX of seller and buyer zone) works correctly.

-- Bujums (c643e83b-229b-4ec4-82e2-8872bf1ac4ba) → agenskalna
UPDATE listings SET locker_id = 'agenskalna'
  WHERE seller_id = 'c643e83b-229b-4ec4-82e2-8872bf1ac4ba' AND locker_id IS DISTINCT FROM 'agenskalna';
UPDATE sellers SET home_locker_ids = ARRAY['agenskalna']
  WHERE id = 'c643e83b-229b-4ec4-82e2-8872bf1ac4ba';

-- Oranžās Bumbas (759999dc-6b93-42c3-bbb3-e1cd5ce18ca9) → agenskalna
UPDATE listings SET locker_id = 'agenskalna'
  WHERE seller_id = '759999dc-6b93-42c3-bbb3-e1cd5ce18ca9' AND locker_id IS DISTINCT FROM 'agenskalna';
UPDATE sellers SET home_locker_ids = ARRAY['agenskalna']
  WHERE id = '759999dc-6b93-42c3-bbb3-e1cd5ce18ca9';

-- WILD’N’FREE (649f58aa-fc57-4ec4-9ec9-c76fbb77e5e9) → agenskalna
UPDATE listings SET locker_id = 'agenskalna'
  WHERE seller_id = '649f58aa-fc57-4ec4-9ec9-c76fbb77e5e9' AND locker_id IS DISTINCT FROM 'agenskalna';
UPDATE sellers SET home_locker_ids = ARRAY['agenskalna']
  WHERE id = '649f58aa-fc57-4ec4-9ec9-c76fbb77e5e9';

-- K/S "Ekoloģisks.lv" (626ac3b7-1546-4099-8061-fb9d0c4f92a3) → brivibas
UPDATE listings SET locker_id = 'brivibas'
  WHERE seller_id = '626ac3b7-1546-4099-8061-fb9d0c4f92a3' AND locker_id IS DISTINCT FROM 'brivibas';
UPDATE sellers SET home_locker_ids = ARRAY['brivibas']
  WHERE id = '626ac3b7-1546-4099-8061-fb9d0c4f92a3';

-- Cake Break (caa3bad0-2689-4feb-b365-93bda00ab429) → brivibas
UPDATE listings SET locker_id = 'brivibas'
  WHERE seller_id = 'caa3bad0-2689-4feb-b365-93bda00ab429' AND locker_id IS DISTINCT FROM 'brivibas';
UPDATE sellers SET home_locker_ids = ARRAY['brivibas']
  WHERE id = 'caa3bad0-2689-4feb-b365-93bda00ab429';

-- "Dabas" not found in sellers table — skipped.

-- austeru bārs BURŽUJS (1210d7d7-bb2b-4c0c-a581-c8890667717e) → brivibas
UPDATE listings SET locker_id = 'brivibas'
  WHERE seller_id = '1210d7d7-bb2b-4c0c-a581-c8890667717e' AND locker_id IS DISTINCT FROM 'brivibas';
UPDATE sellers SET home_locker_ids = ARRAY['brivibas']
  WHERE id = '1210d7d7-bb2b-4c0c-a581-c8890667717e';
UPDATE sellers SET courier_pickup_address = 'Dzirnavu iela 67, Rīga, LV-1010 (Berga bazārs, Buržujs restorāns)'
  WHERE id = '1210d7d7-bb2b-4c0c-a581-c8890667717e';
