export type EventType =
  | "Zemnieku tirgus"
  | "Stādu tirgus"
  | "Gadatirgus"
  | "Pārtikas festivāls"
  | "Amatniecības tirdziņš"
  | "Ziemassvētku tirdziņš"
  | "Sezonāls tirgus";

export type MarketEvent = {
  id: string;
  name: string;
  date: string;       // ISO or "DD.MM–DD.MM.YYYY"
  dateLabel: string;  // human-readable
  month: number;      // 1–12
  city: string;
  region: string;
  venue?: string;
  address?: string;
  type: EventType;
  description: string;
  source?: string;
  recurring?: boolean;
};

export const events: MarketEvent[] = [
  // ── APRĪLIS ──────────────────────────────────────────────
  {
    id: "e1",
    name: "Lauku labumu Zaļais tirdziņš",
    dateLabel: "11. aprīlis",
    date: "2026-04-11",
    month: 4,
    city: "Balvi",
    region: "Latgale",
    address: "Brīvības iela 61C",
    type: "Zemnieku tirgus",
    description: "Pašvaldības rīkots lauku ražotāju zaļais tirdziņš. Zemnieku produkti, amatniecība, mājas pārtika.",
    source: "gadatirgi.lv",
  },
  {
    id: "e2",
    name: "Salaspils pavasara gadatirgus",
    dateLabel: "18. aprīlis",
    date: "2026-04-18",
    month: 4,
    city: "Salaspils",
    region: "Pierīga",
    address: "Inženieru iela 2",
    type: "Gadatirgus",
    description: "Pavasara gadatirgus ar zemnieku produktiem, stādiem un amatniecību. 09:00–15:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e3",
    name: "Jurģu tirgus Dobelē",
    dateLabel: "18. aprīlis",
    date: "2026-04-18",
    month: 4,
    city: "Dobele",
    region: "Zemgale",
    address: "Dobeles vēsturiskais tirgus laukums",
    type: "Gadatirgus",
    description: "Tradicionālais Jurģu tirgus Dobeles vēsturiskajā tirgus laukumā. Zemnieki, lopkopji, amatnieki. 10:00–15:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e4",
    name: "Stādu dienas Dzērvēs",
    dateLabel: "18. aprīlis",
    date: "2026-04-18",
    month: 4,
    city: "Jūrmala",
    region: "Pierīga",
    address: "Kokaudzētava Dzērves, Valles pagasts",
    type: "Stādu tirgus",
    description: "Pavasara stādu tirgus kokaudzētavā. Plašs stādu sortiments dārziem un siltumnīcām.",
    source: "gadatirgi.lv",
  },
  {
    id: "e5",
    name: "Brīvdienu tirdziņš Pļavnieku tirgū",
    dateLabel: "18. aprīlis",
    date: "2026-04-18",
    month: 4,
    city: "Rīga",
    region: "Rīga",
    address: "Andreja Saharova iela 30",
    type: "Amatniecības tirdziņš",
    description: "Unikālas amatniecības preces, rokām darināti adījumi, pārtikas produkti. 09:00–18:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e6",
    name: "Madonas pavasara stādu gadatirgus",
    dateLabel: "25. aprīlis",
    date: "2026-04-25",
    month: 4,
    city: "Madona",
    region: "Vidzeme",
    address: "Saieta laukums",
    type: "Stādu tirgus",
    description: "Pavasara stādu tirgus Madonas saieta laukumā. Dārzeņu stādi, ziedi, sēklas. 08:00–13:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e7",
    name: "Pavasara tirdziņš Valmierā",
    dateLabel: "25. aprīlis",
    date: "2026-04-25",
    month: 4,
    city: "Valmiera",
    region: "Vidzeme",
    address: "Vecpuišu parks",
    type: "Sezonāls tirgus",
    description: "Pavasara tirdziņš Vecpuišu parkā ar zemnieku produktiem un amatniecību. 10:00–15:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e8",
    name: "Pavasara dārza svētki Bulduri",
    dateLabel: "25. aprīlis",
    date: "2026-04-25",
    month: 4,
    city: "Jūrmala",
    region: "Pierīga",
    address: "Bulduru tehnikums, Viestura iela 6",
    type: "Stādu tirgus",
    description: "Pavasara dārza un stādu svētki Bulduru tehnikumā. Augi, stādi, dārzkopības preces. 09:00–16:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e9",
    name: "Pavasara tirdziņš Pļavnieku tirgū",
    dateLabel: "25. aprīlis",
    date: "2026-04-25",
    month: 4,
    city: "Rīga",
    region: "Rīga",
    address: "Andreja Saharova iela 30",
    type: "Zemnieku tirgus",
    description: "Zemnieku produkti (arī no citām valstīm), amatnieku izstrādājumi, mājas pārtika. 09:00–18:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e10",
    name: "Lido zivis un svētku tirgi Kuldīgā",
    dateLabel: "25. aprīlis",
    date: "2026-04-25",
    month: 4,
    city: "Kuldīga",
    region: "Kurzeme",
    address: "Ēdoles iela 50",
    type: "Pārtikas festivāls",
    description: "Zivju tirgus un svētku tirdziņš ar vietējo ražotāju produktiem. 09:00–18:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e11",
    name: "Tirgus Valkā",
    dateLabel: "25. aprīlis",
    date: "2026-04-25",
    month: 4,
    city: "Valka",
    region: "Vidzeme",
    address: "Valkas–Valgas dvīņu pilsētas centrs",
    type: "Gadatirgus",
    description: "Latvijas–Igaunijas robežpilsētas kopīgais tirgus. Zemnieku produkti, amatniecība. 09:00–15:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e12",
    name: "Lielais Jurģu tirgus Preiļos",
    dateLabel: "26. aprīlis",
    date: "2026-04-26",
    month: 4,
    city: "Preiļi",
    region: "Latgale",
    address: "Svētku laukums",
    type: "Gadatirgus",
    description: "Tradicionālais Jurģu gadatirgus ar kultūras programmu, zemnieku un amatnieku precēm. 09:00–13:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e13",
    name: "Lielais aprīļa tirgus Limbažos",
    dateLabel: "26. aprīlis",
    date: "2026-04-26",
    month: 4,
    city: "Limbaži",
    region: "Vidzeme",
    address: "Limbažu tirgus",
    type: "Gadatirgus",
    description: "Lielais pavasara gadatirgus Limbažu tirgū. Zemnieki, lopkopji, amatnieki, pārtikas ražotāji. 08:00–15:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e14",
    name: "Pavasara gadatirgus Lielvārdē",
    dateLabel: "26. aprīlis",
    date: "2026-04-26",
    month: 4,
    city: "Lielvārde",
    region: "Pierīga",
    address: "Lāčplēša laukums",
    type: "Gadatirgus",
    description: "Pavasara gadatirgus Lāčplēša laukumā ar vietējo ražotāju produktiem. 09:00–14:00.",
    source: "gadatirgi.lv",
  },

  // ── MAIJS ─────────────────────────────────────────────────
  {
    id: "e15",
    name: "SPRING EDITION: Design & Taste",
    dateLabel: "1.–2. maijs",
    date: "2026-05-01",
    month: 5,
    city: "Rīga",
    region: "Rīga",
    address: "Esplanāde",
    type: "Amatniecības tirdziņš",
    description: "Dizaina un garšas tirdziņš Esplanādē ar pārtikas ražotājiem, mājas amatniecību un delikatesēm. 11:00–18:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e16",
    name: "Stādu parāde Siguldā",
    dateLabel: "1.–2. maijs",
    date: "2026-05-01",
    month: 5,
    city: "Sigulda",
    region: "Vidzeme",
    type: "Stādu tirgus",
    description: "Siguldas ikgadējā stādu parāde — lielākais stādu tirgus Vidzemē. Stādi, ziedi, dārza preces.",
    source: "eventpartner.lv",
  },
  {
    id: "e17",
    name: "Šlokenbekas burziņš",
    dateLabel: "2. maijs",
    date: "2026-05-02",
    month: 5,
    city: "Tukuma novads",
    region: "Kurzeme",
    address: "Šlokenbekas muiža, Smārdes pagasts",
    type: "Gadatirgus",
    description: "Pavasara gadatirgus muižas parkā. Vietējo ražotāju produkti, amatniecība, kultūras programma. 10:00–15:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e18",
    name: "Stādu tirgus Ogrē",
    dateLabel: "1. maijs",
    date: "2026-05-01",
    month: 5,
    city: "Ogre",
    region: "Pierīga",
    address: "Ogres novada Kultūras centrs",
    type: "Stādu tirgus",
    description: "Ikgadējais stādu tirgus ar plašu dārzeņu, ziedu un augļu stādu klāstu. 10:00.",
    source: "kaskurkad.lv",
  },
  {
    id: "e19",
    name: "Mātes dienas tirdziņš Mežaparkā",
    dateLabel: "10. maijs",
    date: "2026-05-10",
    month: 5,
    city: "Rīga",
    region: "Rīga",
    address: "Mežaparks",
    type: "Sezonāls tirgus",
    description: "Mātes dienai veltīts tirdziņš ar ziedu, amatniecības un pārtikas produktiem. 11:00.",
    source: "kaskurkad.lv",
  },
  {
    id: "e20",
    name: "Latvijas Stādu dienas",
    dateLabel: "9.–10. maijs",
    date: "2026-05-09",
    month: 5,
    city: "Jelgava",
    region: "Zemgale",
    address: "Hercoga Jēkaba laukums",
    type: "Stādu tirgus",
    description: "Latvijas lielākais stādu tirgs Jelgavā. Audzētāji no visas Latvijas. Profesionāli un hobija dārzkopji.",
    source: "eventpartner.lv",
  },
  {
    id: "e21",
    name: "Lauku labumu Zaļais tirdziņš Balvos",
    dateLabel: "9. maijs",
    date: "2026-05-09",
    month: 5,
    city: "Balvi",
    region: "Latgale",
    address: "Brīvības iela 61C",
    type: "Zemnieku tirgus",
    description: "Ikmēneša zaļais tirdziņš ar vietējo zemnieku un ražotāju produktiem. 09:00–13:00.",
    source: "gadatirgi.lv",
  },
  {
    id: "e22",
    name: "Medusmaizes svētki Jersikā",
    dateLabel: "23. maijs",
    date: "2026-05-23",
    month: 5,
    city: "Jersika, Līvāni",
    region: "Latgale",
    address: "Bucenieku stadions",
    type: "Pārtikas festivāls",
    description: "Medusmaizes svētki ar medum, maizi un Latgales pārtikas tradīcijām. Zemnieku tirdziņš, meistarklases.",
    source: "eventpartner.lv",
  },
  {
    id: "e23",
    name: "Rēzeknes tirgus",
    dateLabel: "24. maijs",
    date: "2026-05-24",
    month: 5,
    city: "Rēzekne",
    region: "Latgale",
    address: "Latgales iela 54",
    type: "Gadatirgus",
    description: "Regulārais gadatirgus ar zemnieku produktiem, amatniecību un Latgales labumiem. 09:00–15:00.",
    source: "gadatirgi.lv",
  },

  // ── JŪNIJS ────────────────────────────────────────────────
  {
    id: "e24",
    name: "Brīvdabas muzeja Gadatirgus",
    dateLabel: "6.–7. jūnijs",
    date: "2026-06-06",
    month: 6,
    city: "Berģi, Rīga",
    region: "Rīga",
    address: "Latvijas Etnogrāfiskais brīvdabas muzejs",
    type: "Gadatirgus",
    description: "Lielākais tradicionālais gadatirgus Latvijā Etnogrāfiskajā brīvdabas muzejā. Zemnieku preces, amatniecība, tautas māksla, ēdieni.",
    source: "eventpartner.lv",
  },
  {
    id: "e25",
    name: "Ikšķiles svētku tirdziņš",
    dateLabel: "13. jūnijs",
    date: "2026-06-13",
    month: 6,
    city: "Ikšķile",
    region: "Pierīga",
    type: "Sezonāls tirgus",
    description: "Ikšķiles pilsētas svētku tirdziņš ar vietējo ražotāju produktiem un amatniecību.",
    source: "ogresnovads.lv",
  },
  {
    id: "e26",
    name: "Lielais Latgales tirgus",
    dateLabel: "20. jūnijs",
    date: "2026-06-20",
    month: 6,
    city: "Ludza",
    region: "Latgale",
    type: "Gadatirgus",
    description: "Lielais Latgales reģionālais tirgus Ludzā — viens no lielākajiem lauku produktu tirgiem austrumu Latvijā.",
    source: "eventpartner.lv",
  },
  {
    id: "e27",
    name: "Jāņu tirdziņi",
    dateLabel: "23.–24. jūnijs",
    date: "2026-06-23",
    month: 6,
    city: "Visa Latvija",
    region: "Visa Latvija",
    type: "Sezonāls tirgus",
    description: "Jāņu svētku tirdziņi visā Latvijā — latvāņu vainagi, siļķes, siers, alus, mājas pārtika. Notiek daudzās pašvaldībās vienlaicīgi.",
    source: "eventpartner.lv",
  },

  // ── JŪLIJS ────────────────────────────────────────────────
  {
    id: "e28",
    name: "Garšo Latgali",
    dateLabel: "10.–11. jūlijs",
    date: "2026-07-10",
    month: 7,
    city: "Rēzeknes novads",
    region: "Latgale",
    type: "Pārtikas festivāls",
    description: "Latgales gastronomijas festivāls ar vietējiem ražotājiem, pavāriem un tautas ēdienu demonstrācijām.",
    source: "eventpartner.lv",
  },
  {
    id: "e29",
    name: "Lielvārdes pilsētas svētku tirgus",
    dateLabel: "25. jūlijs",
    date: "2026-07-25",
    month: 7,
    city: "Lielvārde",
    region: "Pierīga",
    address: "Lāčplēša laukums",
    type: "Sezonāls tirgus",
    description: "Pilsētas svētku tirdziņš ar vietējo ražotāju produktiem, mājas pārtiku un amatniecību.",
    source: "ogresnovads.lv",
  },
  {
    id: "e30",
    name: "Sabile Vīna svētki",
    dateLabel: "25.–26. jūlijs",
    date: "2026-07-25",
    month: 7,
    city: "Sabile",
    region: "Kurzeme",
    type: "Pārtikas festivāls",
    description: "Sabiles vīna svētki — viens no iecienītākajiem vasaras pasākumiem. Vietējais vīns, medus, sieri, lauku produkti.",
    source: "eventpartner.lv",
  },

  // ── AUGUSTS ───────────────────────────────────────────────
  {
    id: "e31",
    name: "Nēģu svētki Carnikavā",
    dateLabel: "22. augusts",
    date: "2026-08-22",
    month: 8,
    city: "Carnikava",
    region: "Pierīga",
    type: "Pārtikas festivāls",
    description: "Carnikavas nēģu svētki — tradicionāls zivju festivāls. Svaigi nēģi, vietējo ražotāju tirdziņš.",
    source: "eventpartner.lv",
  },
  {
    id: "e32",
    name: "Ogres pilsētas svētku tirgus",
    dateLabel: "22. augusts",
    date: "2026-08-22",
    month: 8,
    city: "Ogre",
    region: "Pierīga",
    type: "Sezonāls tirgus",
    description: "Ogres pilsētas svētku gadatirgus ar vietējo pārtikas ražotāju un amatnieku stendiem.",
    source: "ogresnovads.lv",
  },
  {
    id: "e33",
    name: "Piena, Maizes un Medus svētki",
    dateLabel: "29. augusts",
    date: "2026-08-29",
    month: 8,
    city: "Jelgava",
    region: "Zemgale",
    type: "Pārtikas festivāls",
    description: "Tradicionālie Jelgavas svētki, kas slavē pienu, maizi un medu — Zemgales lauksaimniecības simbolus. Tirdziņš, degustācijas.",
    source: "eventpartner.lv",
  },
  {
    id: "e34",
    name: "Lauku svētku tirgus Birzgalē",
    dateLabel: "29. augusts",
    date: "2026-08-29",
    month: 8,
    city: "Birzgale",
    region: "Pierīga",
    type: "Zemnieku tirgus",
    description: "Lauku svētku tirdziņš Birzgalē ar zemnieku produktiem un amatniecību.",
    source: "ogresnovads.lv",
  },

  // ── SEPTEMBRIS ────────────────────────────────────────────
  {
    id: "e35",
    name: "Riga Food 2026",
    dateLabel: "10.–12. septembris",
    date: "2026-09-10",
    month: 9,
    city: "Rīga",
    region: "Rīga",
    address: "Starptautiskais izstāžu centrs Ķīpsala",
    type: "Pārtikas festivāls",
    description: "Baltijas lielākā pārtikas rūpniecības izstāde. 420+ eksponenti, degustācijas, ražotāju tikšanās. Lielisks kontaktu veidošanas forums.",
    source: "bt1.lv/rigafood",
  },
  {
    id: "e36",
    name: "Rudens tirdziņš Ikšķilē",
    dateLabel: "19. septembris",
    date: "2026-09-19",
    month: 9,
    city: "Ikšķile",
    region: "Pierīga",
    type: "Sezonāls tirgus",
    description: "Rudens tirdziņš ar ražas produktiem, konserviem, stādiem un amatniecību.",
    source: "ogresnovads.lv",
  },
  {
    id: "e37",
    name: "Rudens stādu tirgus Ogrē",
    dateLabel: "26. septembris",
    date: "2026-09-26",
    month: 9,
    city: "Ogre",
    region: "Pierīga",
    type: "Stādu tirgus",
    description: "Rudens stādu tirgus — sīpolu stādāmmateriāls, košumkrūmi, daudzgadīgie augi.",
    source: "ogresnovads.lv",
  },
  {
    id: "e38",
    name: "Miķeļdienas gadatirgus",
    dateLabel: "27. septembris",
    date: "2026-09-27",
    month: 9,
    city: "Rēzekne",
    region: "Latgale",
    type: "Gadatirgus",
    description: "Tradicionālais Miķeļdienas ražas gadatirgus — nozīmīgākais rudens tirgus Latgalē. Zemnieku produkti, ražas svinēšana.",
    source: "eventpartner.lv",
  },

  // ── OKTOBRIS ──────────────────────────────────────────────
  {
    id: "e39",
    name: "Rudens tirdziņš Suntažos",
    dateLabel: "3. oktobris",
    date: "2026-10-03",
    month: 10,
    city: "Suntaži",
    region: "Pierīga",
    type: "Sezonāls tirgus",
    description: "Rudens gadatirgus Suntažos ar ražas produktiem un lauku labumiem.",
    source: "ogresnovads.lv",
  },
  {
    id: "e40",
    name: "Miķeļdienas tirgus un Maizes svētki Ķegumos",
    dateLabel: "4. oktobris",
    date: "2026-10-04",
    month: 10,
    city: "Ķegums",
    region: "Pierīga",
    type: "Gadatirgus",
    description: "Tradicionālais Miķeļdienas tirgus apvienots ar Maizes svētkiem. Maizes cepēji, zemnieki, ražas produkti.",
    source: "ogresnovads.lv",
  },
  {
    id: "e41",
    name: "Rudens tirgus Lielvārdē",
    dateLabel: "11. oktobris",
    date: "2026-10-11",
    month: 10,
    city: "Lielvārde",
    region: "Pierīga",
    address: "Lāčplēša laukums",
    type: "Sezonāls tirgus",
    description: "Rudens tirdziņš ar ražas produktiem, ievārījumiem, sieru, medu un amatniecību.",
    source: "ogresnovads.lv",
  },

  // ── NOVEMBRIS / DECEMBRIS ─────────────────────────────────
  {
    id: "e42",
    name: "Rīgas Ziemassvētku tirdziņš",
    dateLabel: "27. nov. – 4. janv.",
    date: "2026-11-27",
    month: 11,
    city: "Rīga",
    region: "Rīga",
    address: "Doma laukums un Līvu laukums",
    type: "Ziemassvētku tirdziņš",
    description: "Viens no skaistākajiem Ziemassvētku tirdziņiem Eiropā. Roku darbs, pārtika, sveces, dekorācijas, karstvīns.",
    source: "eventpartner.lv",
  },
  {
    id: "e43",
    name: "Ziemassvētku tirdziņš Ikšķilē",
    dateLabel: "13. decembris",
    date: "2026-12-13",
    month: 12,
    city: "Ikšķile",
    region: "Pierīga",
    type: "Ziemassvētku tirdziņš",
    description: "Ikšķiles Ziemassvētku tirdziņš ar rokdarbu, mājas pārtikas un dāvanu stendiem.",
    source: "ogresnovads.lv",
  },
  {
    id: "e44",
    name: "Ziemassvētku tirgus Ogrē",
    dateLabel: "20. decembris",
    date: "2026-12-20",
    month: 12,
    city: "Ogre",
    region: "Pierīga",
    type: "Ziemassvētku tirdziņš",
    description: "Ogres Ziemassvētku priekšvakarā tirdziņš ar rokdarbu, pārtikas un dāvanu ražotājiem.",
    source: "ogresnovads.lv",
  },
  {
    id: "e45",
    name: "Ziemas tirdziņš Valmierā",
    dateLabel: "Decembris",
    date: "2026-12-01",
    month: 12,
    city: "Valmiera",
    region: "Vidzeme",
    type: "Ziemassvētku tirdziņš",
    description: "Valmieras Ziemassvētku tirdziņš pilsētas centrā ar vietējo ražotāju un amatnieku stendiem.",
    source: "gadatirgi.lv",
  },

  // ── REGULĀRI ──────────────────────────────────────────────
  {
    id: "e46",
    name: "Kalnciema kvartāla zemnieku tirgus",
    dateLabel: "Katru sestdienu",
    date: "2026-01-01",
    month: 0,
    city: "Rīga",
    region: "Rīga",
    address: "Kalnciema iela 35",
    type: "Zemnieku tirgus",
    description: "Rīgas populārākais zemnieku tirgus katru sestdienu. Latvijas lauku ražotāji, bioloģiskie produkti, siers, medus, gaļa, maize. 10:00–16:00.",
    recurring: true,
    source: "kalnciemaiela.lv",
  },
  {
    id: "e47",
    name: "Rīgas Centrāltirgus",
    dateLabel: "Katru dienu",
    date: "2026-01-01",
    month: 0,
    city: "Rīga",
    region: "Rīga",
    address: "Nēģu iela 7",
    type: "Zemnieku tirgus",
    description: "Viens no lielākajiem tirgiem Eiropā. Vietējo zemnieku produkti — gaļa, zivis, dārzeņi, piens, maize. Darba laiks: 07:00–18:00.",
    recurring: true,
    source: "centraltirgus.lv",
  },
];

export const months: Record<number, string> = {
  0: "Regulāri",
  4: "Aprīlis",
  5: "Maijs",
  6: "Jūnijs",
  7: "Jūlijs",
  8: "Augusts",
  9: "Septembris",
  10: "Oktobris",
  11: "Novembris",
  12: "Decembris",
};

export const typeColors: Record<EventType, string> = {
  "Zemnieku tirgus":      "bg-green-100 text-green-800",
  "Stādu tirgus":         "bg-lime-100 text-lime-800",
  "Gadatirgus":           "bg-amber-100 text-amber-800",
  "Pārtikas festivāls":   "bg-orange-100 text-orange-800",
  "Amatniecības tirdziņš":"bg-purple-100 text-purple-800",
  "Ziemassvētku tirdziņš":"bg-red-100 text-red-800",
  "Sezonāls tirgus":      "bg-sky-100 text-sky-800",
};

export const typeEmoji: Record<EventType, string> = {
  "Zemnieku tirgus":      "🌿",
  "Stādu tirgus":         "🌱",
  "Gadatirgus":           "🏪",
  "Pārtikas festivāls":   "🍎",
  "Amatniecības tirdziņš":"🏺",
  "Ziemassvētku tirdziņš":"🎄",
  "Sezonāls tirgus":      "📅",
};
