-- Add SEO-friendly slug column to listings.
-- Slugs are generated by the application (lib/utils.ts toUniqueSlug) when
-- listings are created via the product form.
-- Existing listings must be backfilled using scripts/backfill-slugs.mjs.

-- Step 1: Add nullable column (no UNIQUE yet — allows NULL for old rows)
ALTER TABLE listings ADD COLUMN IF NOT EXISTS slug TEXT;

-- Step 2: Index for fast slug lookups
CREATE INDEX IF NOT EXISTS listings_slug_idx ON listings (slug) WHERE slug IS NOT NULL;

-- Step 3: After running backfill-slugs.mjs, add UNIQUE constraint:
--   ALTER TABLE listings ADD CONSTRAINT listings_slug_unique UNIQUE (slug);
-- (Do NOT run this line until the backfill script has populated all rows)
